{
 "title": "AmneziaWG",
 "description": "Metrics for AmneziaWG VPN",
 "tags": [
  "amneziawg",
  "wireguard",
  "vpn"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Current time range", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traffic Summary",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(awg_sent_bytes[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clients traffic",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 16, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(awg_sent_bytes[$__range]) != 0",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Clients traffic",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(awg_sent_bytes[$__range]) != 0",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Latest Handshakes",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - awg_latest_handshake_seconds < 2592000",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Received/Sent Bytes Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(awg_sent_bytes[$__rate_interval]) != 0",
     "legendFormat": "Sent {{client_name}}"
    },
    {
     "expr": "rate(awg_received_bytes[$__rate_interval]) != 0",
     "legendFormat": "Received {{client_name}}"
    }
   ]
  },
  { "title": "All the time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Clients Summary Traffic",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "awg_sent_bytes", "legendFormat": "{{client_name}}" }
   ]
  },
  {
   "title": "Clients Summary Traffic",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "awg_sent_bytes != 0", "legendFormat": "{{client_name}}" }
   ]
  },
  {
   "title": "Hidden",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inactive Users",
     "type": "stat",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "awg_sent_bytes == 0", "legendFormat": "{{client_name}}" }
     ]
    }
   ]
  }
 ]
}